### ISSUE TITLE
No unified inbox, but want sent emails showed in each inbox

### ISSUE THREAD

**Issue by gaomy3832** [protz/GMail-Conversation-View#1004]
I did a quick search on the previous issues but didn't find a solution, so apologize if this is a duplicated question.

I prefer to have each inbox separate, and I know how to cancel the unified inbox. However, after I revert to separate inbox, sent emails stop showing in the inbox.

I do remember this was possible before. However, I recently upgraded my OS to win 10 and reinstalled Thunderbird, and I can't make it happen any more. I am now using Thunderbird 38.2.0 and Conversation 2.10. Is this because Thunderbird or Conversation changed? Is there a way to restore this?

Thanks!

**Comment by msprotz** [comment]
I don't think it was possible before to have separate inboxes where sent messages also show up in the inbox (the "thread pane", a.k.a. message list). The unified inbox is the only folder which you can configure to aggregate multiple regular folders.

**Comment by msprotz** [comment]
(Please close this issue if that answers your question. Thanks!)

**Comment by gaomy3832** [comment]
The sent emails were not shown in the thread pane, but in the message pane. Just like Gmail web interface, if I select an entire thread in the thread pane, all the emails in this thread will be shown in the message pane, including sent and received. Currently only received emails are in the message pane.

**Comment by msprotz** [comment]
So you mean that the conversation view is failing to find related messages in the conversation from *other folders*?

**Comment by gaomy3832** [comment]
Exactly. Sorry for my bad description.

**Comment by msprotz** [comment]
Yeah that sounds like an issue with gloda, the global indexer. Did you tweak any settings related to indexing?

**Comment by gaomy3832** [comment]
I didn't do anything intentionally, but may be I changed something long time ago and I don't remember. I've tried disabling other add-ons but with no good.

**Comment by protz** [comment]
Hmm... see the FAQ and try to follow the instructions about deleting 
global-messages-db.sqlite. Also, you should check before that your sent 
folder is indeed being indexed (right-click, properties, something I 
don't remember, then make sure "include this folder in global search 
results" is checked).

**Comment by gaomy3832** [comment]
OK. I am now away from my personal computer on which Thunderbird is installed. I will try your suggestions when back home and let you know.

Thanks for the help!

**Comment by gaomy3832** [comment]
I tried delete global-messages-db.sqlite to force it rebuild the index, and this solved my issue.

Thanks for the solution!
