### ISSUE TITLE
Conflicts with change quote add-on

### ISSUE THREAD

**Issue by AlexStarc** [protz/GMail-Conversation-View#355]
SW: Windows XP SP3
        Thunderbird v. 5.0 plus:
              Change quote and reply format 0.7.4.1 (https://nic-nac-project.org/~kaosmos/changequote-en.html or )
              Thunderbird Conversations 2.0.8

Steps to reproduce:
1. Setup change quote add-on to use custom reply header to smth like this:
<br>
<font face="Calibri, body" size="2">
Thanks in advance,
Alexander</font></p>
    -------- Original Message --------
    <b>From: </b>%%1
    <b>Sent: </b>%%5
    <b>To: </b>%%2{{</br>    <b>Cc: </b>%%3}}
    <b>Subject: </b>%%4

2. From conversation view select reply / reply all button at the bottom of message;
3. Observe reply header displayed correctly;
4. Try to reply to another message from another conversation;

Actual results:
Header with old recipients observed;

Expected results:
Header with correct recipients observed.

Additional info:
The issue is not reproducible with using 'view using classic reader' option in conversation or with Thunderbird Conversation disabled.

**Comment by protz** [comment]
closing since really there's nothing I can do here
