### ISSUE TITLE
The quick reply is closed when a new thread reply is received

### ISSUE THREAD

**Issue by jdale88** [protz/GMail-Conversation-View#364]
If you are typing a reply to a message using the quick reply feature, and a new reply to the thread you are replying to is received whilst you are typing, the quick reply will be closed.

This is really bad behaviour (despite the contents of your reply being saved if you then quick reply to the new message) as it closes the quick reply and results in you accidentally typing in commands (I accidentally archived some email because of this!).

If you **have** to close the quick reply when a new message is received in the current thread, then you should really automatically re-open it on the newly received message to save your users typing into nothing.

Steps to reproduce:
1. Have someone send you an email.
2. Open the quick reply to respond to that email.
3. Have them send a reply to their original email.
4. The quick reply will now be closed.

**Comment by protz** [comment]
#730 (duplicate)
