### ISSUE TITLE
Enigmail / OpenPGP: Attachments not encrypted when using Quick Reply.

### ISSUE THREAD

**Issue by ddidderr** [protz/GMail-Conversation-View#640]
When using the Quick Reply field below the message, attachments are NOT encrypted. And nobody is asking me, nor warning me about that.

If I send attachments using the default Reply Dialog everything works fine and it uses my default settings (I use PGP/MIME as default.) But the Quick Reply is ignoring it completely.

Please add at least a warning about that! Today I was sending an attachment unencrypted, which wasn't intended to be unencrypted...

But all in all: REALLY NICE AND GREAT ADD-ON!  I CAN'T THINK ABOUT THE TIMES WHERE I  HAD TO LIVE WITHOUT IT!!!

**Comment by protz** [comment]
Closing in favor of #791
