### ISSUE TITLE
Context menu disappears (OS X)

### ISSUE THREAD

**Issue by pfarmer821** [protz/GMail-Conversation-View#647]
Strange things are happening with my context menu (command-click or right click) when using Thunderbird Conversations.

If I am in classic view, the context menu works just fine.  Immediately after I enable Thunderbird Conversations, the context menu works just fine.  But if I quit Thunderbird with Conversations enabled, and then restart Thunderbird, the context menu disappears -- nothing happens with a command-click or right-click when my cursor is in the message preview pane.

(The workaround is to disable and then re-enable Thunderbird Conversations each time I start up Thunderbird, but that's a bit clumsy.)

I am using Thunderbird 16.0 and Thunderbird Conversations 2.4.1 on Mac OS X 10.8.2.

Pete Farmer

**Comment by protz** [comment]
Closing (a Thunderbird issue in any case)
