### ISSUE TITLE
Reply to List disappeared in recent update

### ISSUE THREAD

**Issue by msc-** [protz/GMail-Conversation-View#651]
Reply to List disappeared from the "More" pull-down menu with some recent revision of Conversations or TBird. I'm using Conversations 2.4.3 in TBird 15.0.1 on Windows XP.

I have verified that the appropriate headers are still present in the mail messages and Reply to List still appears in the TBird Message menu and is enabled for the messages in question.

Please bring it back. It's a very useful feature.

**Comment by protz** [comment]
#781 (closing in favor of the more recent issue)
