### ISSUE TITLE
After failure to send message, display issue and cannot show popout reply

### ISSUE THREAD

**Issue by dotancohen** [protz/GMail-Conversation-View#665]
I have two mailservers configured, and the Quick Reply only lets one send mail from the default mailserver. When an attempted send failed, the textarea seems to have "grown" a few pixels to the left and the Reply popup button is now hidden and cannot be pressed. Resizing the message pane by moving the splitter between the list pane and the message pane did not resolve the issue. Unmaximizing then remaximizing the Thunderbird window did not resolve the issue. Switching to a different message then switching back _did_ resolve the issue.

See attached screenshot.

Thunderbird 16.0.1, Conversations 2.5.2, Kubuntu Linux 12.10

Thanks.

![Screenshot displaying issue](http://img690.imageshack.us/img690/9822/conversationsg.png)

**Comment by protz** [comment]
Closing until further steps to reproduce are found
