### ISSUE TITLE
Show conversation folder names

### ISSUE THREAD

**Issue by jturner314** [protz/GMail-Conversation-View#667]
One extremely useful feature of Gmail is that the user can see the labels for all of the messages in a conversation at the top of the conversation thread.  (See [this image](http://zapp5.staticworld.net/images/article/2011/10/new-gmail-3-5228556.jpg) as an example.)  It would be awesome to to have a similar feature in Thunderbird Conversations (displaying all of the folders that a conversation's messages are in), so that filing messages would be much more straightforward.  I would recommend putting the folder names beside the subject line.

**Comment by protz** [comment]
Closing (vague, major rework of both Thunderbird and Conversations, nothing that can be fixed in the near future)
