### ISSUE TITLE
Exclamation mark at top left corner in PDF preview

### ISSUE THREAD

**Issue by thonixx** [protz/GMail-Conversation-View#695]
Hi, I love the addon but now I have an issue which is a little bit annoying.
Sporadically there are exclamation marks in top left corner of a PDF.

I can't see a pattern yet but here an example where the exclamation mark should not be:
http://ubuntuone.com/3VSKAUKYtn1BEVc5sBRBev

(I can not show you more of the PDF, it is confidential.)
Do you need any more informations? Do not hesitate to comment, I can give you more where it is needed.

***
*Versions*
Thunderbird: 17.0.2
Addon: 2.5.2

**Comment by protz** [comment]
Closing (pdf.js issue)
