### ISSUE TITLE
Encoding problem at viewing PDF

### ISSUE THREAD

**Issue by thonixx** [protz/GMail-Conversation-View#696]
I have another PDF viewer issue. With evince and any other PDF viewer I sporadically have the problem of bad encoding.

Here an example:
http://ubuntuone.com/38um3rNNKDB5LSqliWCIRR

And the pdf with pdf.js is also correct.
ps: I sent you a mail with a bad encoded PDF.

**Comment by protz** [comment]
Closing (pdf.js issue)
