### ISSUE TITLE
Unreadable PDF

### ISSUE THREAD

**Issue by thonixx** [protz/GMail-Conversation-View#697]
Sorry, to bother you again with the PDF viewer but I think something is broken again. I use the same versions of plugin and thunderbird as before and I still run into issues. For example I attached an image which demonstrates the issue.

![Screenshot from 2013-02-11 11:10:28](https://f.cloud.github.com/assets/1019034/144692/80d650ae-7433-11e2-95fc-5ddcbe45187a.png)

Still the PDF looks normal in evince and any other PDF viewer (also in the web version of the JS PDF viewer). Should I forward it to your mail address?

**Comment by protz** [comment]
Closing (pdf.js issue)
