### ISSUE TITLE
Slight formatting issue with horizontally resizing windows

### ISSUE THREAD

**Issue by davenz** [protz/GMail-Conversation-View#720]
Hi All, 

First, thanks for this great add-on. I've come across a wee formatting issue, reproducible in Thunderbird 17.04 on Mac OS 10.8.3 with the latest Thunderbird Conversations installed, and the same in Earlybird 21.0a2 on Windows 7. 

In this first screengrab you can see the "show details | reply | more" menu at the far right of an open message in a conversation:

http://ubuntuone.com/0vtZWRV4L7HyWl4FLkIHPD

In this second screengrab the window is being horizontally resized. As I do this, this particular element doesn't appear to wrap, to the point where the menu will eventually not be visible at all (whereas all the other content does nicely):

http://ubuntuone.com/49TsIsBlpfrwJnggnYd1iW

Let me know if you need any more information :)

Cheers, 
Dave

**Comment by protz** [comment]
I believe this has been fixed recently by the changes to the heade,r that now uses css flex boxes

**Comment by davenz** [comment]
A belated thank-you for the fix!

Cheers, 
Dave
