### ISSUE TITLE
Wrong encoding with cyrillic names

### ISSUE THREAD

**Issue by andrewb3000** [protz/GMail-Conversation-View#721]
Hi!
Addressee's name with cyrillic letters is shown incorrectly.

![cyr-name-issue](https://f.cloud.github.com/assets/4004072/317287/531f2996-9865-11e2-81cd-1c52d080d8bf.png)

**Comment by protz** [comment]
Closing in favor of the more recent #924

**Comment by zsdedan** [comment]
Hi, I have this issue after upgrade to version 45.5.1.
OS Ubuntu 16.10
![bugreport-conversations](https://cloud.githubusercontent.com/assets/3087460/20875522/d2f0c82e-bad4-11e6-93a5-eb96965a35e2.png)

I sent to your e-mail message with wrong encoding.
