### ISSUE TITLE
Archive conversations

### ISSUE THREAD

**Issue by namise** [protz/GMail-Conversation-View#742]
Hi,

Can you please make an enhancement to the Archive function which is to archive all emails of a conversation (included sent emails) to a select-able folder rather than the default Archives folder only ? I'd like to have a function that

1) When I moved the 1st email of a conversation to a folder, the folder will be remembered so I can file consequent emails of that conversation into the folder with one click.

2) If the 1st email is not filed yet, when I click the Archive button then a dialog will open to select a folder then filling all related emails of the conversation into that folder.

The requested function behaves similarly to the ClearContext add-on for MS Outlook. 

Thanks & best regards,
Namise

**Comment by protz** [comment]
Closing since that's a lot of work for a minor enhancement, and I don't think anyone can afford to fix this right now.
