### ISSUE TITLE
Be able to import attached PGP keys with Enigmail

### ISSUE THREAD

**Issue by NicoHaase** [protz/GMail-Conversation-View#747]
Hi there,
after a keysigning party, the popular tool caff sends the signed keys as attachments to their owner. In the standard mail view of Thunderbird, Enigmail allows me to directly import these keys into my keyring. If the mail is shown using your addon, there is no direct way to import the keys, as there is no context menu entry by Enigmail.

**Comment by protz** [comment]
I'd say this falls under the umbrella of #791
