### ISSUE TITLE
Keyboard commands in a message in a tab don't work

### ISSUE THREAD

**Issue by RimpelF** [protz/GMail-Conversation-View#810]
When opening a message in a new tab you can't directly use the keyboard e.g. you can't use the cursors to scroll or del to delete the message.
This is due to whatever window has the focus as pressing tab gives the main msg panel the focus and then the keyboard can be used as expected.

Can we change the initial focus so that the keyboard works immediately?

cheers

**Comment by protz** [comment]
That's #333 and it's significant work, unfortunately...

Thanks for reporting, though!
