### ISSUE TITLE
Bug: plugin sometimes open links withing itself instead of external web browser

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [protz/GMail-Conversation-View#815]
Can you please allow us to choose that clicking anywhere on the email letter would open the default web browser, and avoid having it on thunderbird itself?

EDIT: it seems that it's a bug, though I was sure it was a feature...
Anyway, please let the plugin open links in the external default web browser, always.

**Comment by protz** [comment]
(Closing since I fixed the original issue I believe, then the conversation drifted into compatibility issues with another addon.)
