### ISSUE TITLE
Conversation threading sometimes mixes two separate email threads

### ISSUE THREAD

**Issue by edmorley** [protz/GMail-Conversation-View#840]
I see this happening fairly frequently, eg:

![screenshot1](https://cloud.githubusercontent.com/assets/501702/3779872/fec5da80-1986-11e4-9efe-eeb01befffb4.png)

In this case, a Github notification email thread has had a Confluence notification email appended. Note also how the subject shown in the email list up top, differs from that shown in the banner between the email list and the message content.

Has been happening for a while, but the example above was with http://jonathan.xulforum.org/files/gcv-nightlies/201407311428-master.xpi and Thunderbird Daily 2014-07-23

Let me know which bits of the headers are relevant, and I'll dump them here (the Github ones contain tokens iirc, so slightly reluctant to paste as is).

**Comment by amitlan** [comment]
Seeing this as well.

**Comment by petervangalen** [comment]
This is really annoying. By the way Apple Mail has the same problem.

**Comment by orschiro** [comment]
Maybe the newly employed full-time employee of SoftMaker can improve the threading backend of Thunderbird?

http://www.reddit.com/r/linux/comments/2zgfer/softmaker_includes_thunderbird_in_softmaker/

**Comment by roughnecks** [comment]
Too bad.
This add-on is useless until this bug gets fixed.
