### ISSUE TITLE
Attachments do not display with Thunderbird 31

### ISSUE THREAD

**Issue by athompso** [protz/GMail-Conversation-View#841]
I've deleted the global-message-db.sqlite file, restarted Thunderbird 31, and confirm that attachments still do not display at all, on any message, no matter how they're encoded or attached.
The FAQ also mentions that I should update to a nightly build from 2011... I assume that advice is now obsolete?
I have tried disabling all other extensions in case it was a new incompatibility, but that produced no change, either.

**Comment by jfburkhart** [comment]
Excellent. 'I love attachments' fixed for me: Ubuntu 14.04, TB 31.4.0

**Comment by jmadero** [comment]
This is still an issue for me. Ubuntu 14.10, TB 31.5.0.

I love attachments does not fix it;
Adding the additional add on "Show all body parts" and enabling I love attachments does not fix it;
The idea of making all of my emails available offline is somewhat problematic as I have about 100k emails over a few accounts . . . downloading all of these seems not ideal.

I'm willing to forward an email or two but I have to figure out which ones are confidential and which ones I can share.

**Comment by msprotz** [comment]
Something broke in Thunderbird and I need to fix it. This is at the very top of my to-do list :)

**Comment by guettli** [comment]
I  have the same issue. I think the work around (show message in classic layout) should be in the FAQ.

**Comment by protz** [comment]
Thanks. A fix is underway on the Thunderbird side, we just need to wait for it to make it in the official builds.

**Comment by gurvinderdadyala** [comment]
@protz Great News

**Comment by kolewu** [comment]
Is it possible to deliver this fix with the help of a plugin?

**Comment by protz** [comment]
Quite regrettably, not. The fix touches a core part of Thunderbird. I'm
fairly confident that the fix will make it into the next release, though.

**Comment by biancardi** [comment]
has this been fixed?  It just started to break today for me and is inconsistent - some attachments show up fine and others do not.

**Comment by protz** [comment]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1096127 ; the patch has 
not currently landed on the Thunderbird side.

**Comment by biancardi** [comment]
thanks - if anyone wants my header info, I will be happy to send them.  The attachment shows up fine in gmail, but thunderbird refuses to display it and instead gives me that mime-encoded blurb in the body of  the email (that is supposed to be my csv file).  I am sending emails from servers (these are normal logs/error emails) and it just broke this morning.  It was working yesterday.  It doesn't happen with all attachments - I get emails from other people with attachments and it is fine.  Just these...

strange.

**Comment by protz** [comment]
Closing since the fix has made it to both Nightly and Aurora.

**Comment by biancardi** [comment]
How do I get the fix?  my thunderbird states it is up to date, but I still do not see any difference with those emails that I had the issue with.  I am on 31.5.0 and I just sent an attachment from my server and the same funky looking mime encoding.

begin 755 gui.txt
3+V]P="]T9&DW,B]I8FUD:71K"@``
`
end

It renders the attachment fine as a .txt file under the gmail web interface, which I loathe.

**Comment by protz** [comment]
I think you're experiencing a different issue. Please forward the email to me using Message > Forward As > Attachment.

**Comment by biancardi** [comment]
Hi Jonathon, I sent you two emails - one from thunderbird which the attachment won't render (as t-bird doesn't recognize it) and the other from the google mail web gui interface, which does render the attachment just fine.  Let me know if you received them - I send them from my business account that ends with @bc.edu

thanks so much
michele

**Comment by deanfourie1** [comment]
Sorry to bring this old chestnut up again, but I just installed the latest version of Ubuntu 22.04 and I am having this exact issue in Thunderbird.

All folders are selected to download for offline use, yet still no attachments are showing in the email.

Any ideas?
