### ISSUE TITLE
Replace pdf.js with viewer.js for more preview options

### ISSUE THREAD

**Issue by trenkert** [protz/GMail-Conversation-View#843]
Can you replace pdf.js with viewer.js (http://viewerjs.org/)?

Viewerjs integrates pdf.js but also WebODF which provides the ability to also view - and edit! - odf documents (see here: http://www.webodf.org/demo/ci/wodotexteditor-0.5.2/localeditor.html).

Use case: I often get documents for review where I have to make some minor changes before sending them back. Traditionally, I have to save the attachment, open Libreoffice or Word, make the changes, save them, and write a response with the altered file as an attachment.

If WebODF can be integrated with Thunderbird, this should only be two step instead of five.

Also, I think this would be a great addition to Thunderbird Conversations at a relatively low cost!

**Comment by protz** [comment]
Closing since it a significant amount of work that I don't intend on pursuing myself.
