### ISSUE TITLE
Ctrl+r doesnt work from message list 

### ISSUE THREAD

**Issue by hsundar** [protz/GMail-Conversation-View#844]
I am using v 2.8.1 on Thunderbird 31.0

In the message list--only for conversations---I am unable to use Ctrl+r to reply to a message. This does not happen for single emails. I am also able to hit tab to move from the message list to the actual message and then use Ctrl+r to reply. Expanding the thread in the message list, and selecting a specific message before using Ctrl+r also works.

**Comment by protz** [comment]
I think that's Thunderbird code that's responsible for that, so you're better off filing a bug there.

Thanks,

Jonathan
