### ISSUE TITLE
Some bugs and some suggestions

### ISSUE THREAD

**Issue by kazakore** [protz/GMail-Conversation-View#851]
I hope you don't mind me using here for a kinda feedback plus suggestion area. Too much to say to open 5 or 6 difference Issues on GitHub, so if you are willing to look into any of them please make a dedicated Issue to track it in. I hoped here would be better than just leaving a Review though.

**Threads not split at change of email Subject.** (Bug/Request)
This works fine in normal Threaded view but obviously then I'm missing my own replies and it can become hard to read the who thread. This is espcially useful when you are in Mail-lists and subjects branch and progress from previous conversations. Having them all display under the original thread is really counter-intuitive (especially when you can remember the original Subject to find it quickly without Searching) and is not the way it is done within Outlook, Hotmail or Gmail.

**Keyboard Shortcut edit panel will not open on subsequent attempts** (Bug)
Open your Add-On's Preferences, click the button to edit keyboard shortcuts. Close Preferences. Reopen Preferences and try and reopen the Edit Shortcuts area. It will not let you, giving a message that "Another window is already editing hotkeys.  Please use that window instead." even though it isn't. You have to close and reopen the whole of Thunderbird to get back into Keysettings!

**Missing keyboard shortcuts** (Feature Request)
Can we please have shortcuts to Expand/Collapse All. I was very surprised not to find this was already there! Also a shortcut to move to prev/next message within thread when the keyboard focus is in the message pane would be very appreciated! Currently you either have to refocus the mailbox area or reach for the mouse. Neither of which I like doing!

**Option to show Quotes on opening** (Feature Request)
You have it set to hide quotes in each email as default. I would like to show any quotes without having to click on the Show Quotes button. Again especially for longer Mail-list messages, were the original email has often been replied to inline, broken down into chunks, so you really want to see what each bit of the reply is referring to! An option to toggle behaviour in Preferences would be appreciated.

**Own email shown twice in Mail-list threads** (Bug/Request)
Again not how it works in Outlook/Hotmail/Gmail but when you are one of the recipients to the messages you send, because they go to a mail-list, then it get displayed in the thread twice. Once from you receiving it, once from your Send tray. Would it be possible to check for repeated message and only display once?

I think that was it... It may be far from perfect but it's still improved my Thunderbird experience greatly. Although not sure I really like Thunderbird much at all yet really...

**Comment by protz** [comment]
Thanks for the suggestions. I've created the second item as a separate bug, but for all other feature requests, unless you come up with a patch, I don't see myself implementing them anytime soon...

Thanks,

Jonathan
