### ISSUE TITLE
Displays message only after search completed

### ISSUE THREAD

**Issue by riedel** [protz/GMail-Conversation-View#857]
Particularly if a large number of emails is searched, the message body is only displayed after the search has finished while without viewing emails is possible during quick search.

V2.8.1, tb 32.

I remember a different behaviour in earlier versions of either tb or conversion-view. Is currently a show stopper.

**Comment by protz** [comment]
I'm closing this issue since there's nothing really actionable and I'm aware I need to improve the performance.
