### ISSUE TITLE
Regression: Contact tooltip only showing on "Me"

### ISSUE THREAD

**Issue by pianoslum** [protz/GMail-Conversation-View#885]
I just noticed: On the 2.9+ branch the tooltip (when you hover with the mouse over a contact's name in conversation view) doesn't show up (except on "me"). I'm quite surprise as I didn't notice that before! Can someone confirm? It's also possible I srewed up something with my git ;)

It doesn't seem to be due to a recent commit as I tried one from August as well.

**Comment by pianoslum** [comment]
I don't understand too much of that CSS/JQuery/whatever-mixture, but I pinpointed the error to one line:
If `overflow: hidden` is omitted in skin/conversation.css:217 then the popup is shown (the content is a little disarranged, but this could be another issue!?).

Can you make sense of this?

**Comment by protz** [comment]
Seems like the right fix to me. What's wrong with the contents? (I 
couldn't see any defect, except that the github sender has an email 
address that's too long and overflows past the tooltip.)

~ jonathan

**Comment by protz** [comment]
Wait no the comment is right, the text-ellipsis needs this to work. I 
need to think about it a little more.

~ jonathan
