### ISSUE TITLE
Release new version before christmas?

### ISSUE THREAD

**Issue by pianoslum** [protz/GMail-Conversation-View#896]
Some time ago I asked you about releasing a new version... I thought that there a quite a number of fixes, so maybe a release would be justified?
If it's too much stress for you at the moment, it'll be no problem as well - I can build a version for myself ;-)

I tried to think which fixes should be included:

* #848 I don't know what this does but it seems good?
* #861 Absolutely essential! ;-) Just kidding, but it could help new developers building the extension.
* #865 I would like to have this one - could help with some PDF-viewer problems.
* #867 and #883 should be good for users of dark themes
* #868 Pretty minor, but: Why not?
* #879 ditto
* #880 This would be rather important for me, is already in the 2.8-branch
* #882 Should be ok, but maybe needs more testing

I think all commits using the new getIdentities()-syntax should be left out as they aren't tested so much.
Including your two css-related commits would be cool as well, but there's still #885, furthermore I don't know whether they are compatible with older Thunderbird versions.

I have some spare time until Christmas and could help doing whatever is necessary ;-)
Is it "just" cherry-picking the respective commits and then submitting to addons.mozilla ?

**Comment by protz** [comment]
Alright, I've slid into a vortex of life-related issues such as being busy with the new job, doing *a lot* of traveling over the past three months, and having no time for the addon. Things are getting better now, so I'm working through the backlog of issues. The plan is the "emergency one", i.e. try to fix everything, push the required fixes on the Thunderbird side and beg for approval to land them before the Thunderbird 38 release.

I'm sorry I didn't get to do a release in December as you wished. I just had no time, and I'm sorry again about not integrating your pull request even though you did all the cherry-picking...

That being said, if you have any outstanding pull requests that you'd like me to merge, I'm all for it :)
