### ISSUE TITLE
Message Disposition Notification is not displayed

### ISSUE THREAD

**Issue by simonschaufi** [protz/GMail-Conversation-View#900]
When i receive an email where the sender requests a Message Disposition Notification, it is not displayed somewhere. I only see it when i switch to the classic mode. Then a toolbar appears about the request. Can this notification be displayed somwhere in the conversation view also?

**Comment by protz** [comment]
Hi,

Thanks for reporting. That's issue #129. Basically, there's a bunch of cleaning up needed on the Thunderbird side before the addon can implement this properly. If you have some coding skills and the motivation, I'd be more than happy to provide guidance on how to fix this, but I currently don't have time to do this myself.

Best,

Jonathan
