### ISSUE TITLE
Attachments Are Hidden Making Thunderbird Conversations Impossible to Use

### ISSUE THREAD

**Issue by jmadero** [protz/GMail-Conversation-View#903]
Unfortunately this is not 100% reproducible but many times attachments are impossible to see/open. I have seen this time and time again where it's obvious I have an attachment but the attachment isn't possible to get to.

An image is worth a thousand words I suppose. The attached image shows a particular email with a green box around the icon for "attachment" - furthermore the blurred out conversation has a comment about "see attachment." Yet...as you can see there is no way for me to get to the conversation. 

This is not the case for all attachments but at least 25% of them have similar issues. If there's something more I can do to get reproducible steps please let me know and I'll try.

![thunderbirdconversation](https://cloud.githubusercontent.com/assets/1181049/5696021/0c014cf0-9972-11e4-9bcd-79c290d616c1.png)

**Comment by kosturik** [comment]
Everything was OK before, now I have exatly same problem, probably after Thunderbird or plugin update.

**Comment by pianoslum** [comment]
See #841 ; enabling 'Select this folder for offline use' could help...

**Comment by protz** [comment]
Hi,

Thanks for reporting, and sorry about the delay. I've been super busy in real life.

This is #841 so I'm closing this. @pianoslum , huge thanks for doing all the triaging and commenting on bugs.

Thanks,

Jonathan
