### ISSUE TITLE
external editor plugin integration

### ISSUE THREAD

**Issue by Konfekt** [protz/GMail-Conversation-View#905]
How about, if `Ctrl-E` is pressed and the External Editor plugin (http://globs.org/articles.php?pg=2&lng=en) installed, then the External Editor opens (instead of the Compose Template)?

**Comment by protz** [comment]
Hi,

Thanks for the suggestion. I unfortunately don't have any time for new features right now; plus, this would add a tremendous amount of complexity that I can't afford to maintain.

Thanks for understanding,

Jonathan
