### ISSUE TITLE
Group by thread AND date?

### ISSUE THREAD

**Issue by potofcoffee** [protz/GMail-Conversation-View#906]
It would be great if the message list could be grouped by date while still using the threaded view (Outlook does this, for example). Or maybe there's a way to do this already, which I just missed?

**Comment by protz** [comment]
I'm afraid there's no way to do this. There's been several requests to do this in the past (e.g. #315) but unfortunately that's a big engineering effort that I currently don't have the time to pursue.

Thanks for understanding,

Jonathan
