### ISSUE TITLE
from, tos and ccs are overwritten with action buttons in single message view

### ISSUE THREAD

**Issue by andreaschiffo** [protz/GMail-Conversation-View#907]
when showing single message the email's 'from','tos' and 'ccs'  (at the top-left corner of message view) overwrite the action options such as Reply and ReplyToAll that are supposed to be shown on top-right corner of message view
see attachment
below are TB's
![conversation issue_21012014](https://cloud.githubusercontent.com/assets/10629167/5834380/3dd0ce02-a15d-11e4-80ec-4df30e32a984.PNG)
 version information

  Informazioni di base

    Nome: Thunderbird
    Versione: 31.4.0
    User agent: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:31.0) Gecko/20100101 Thunderbird/31.4.0
    Cartella del profilo: Mostra cartella

              (disco locale)
    ID di build dell'applicazione: 20150109111741
    Plugin attivi: about:plugins
    Configurazione build: about:buildconfig
    Utilizzo memoria: about:memory

  Account di posta e news
    account1:
      INCOMING: account1, , (pop3) mail.overit.it:110, alwaysSTARTTLS, passwordCleartext
      OUTGOING: mail.overit.it:25, alwaysSTARTTLS, passwordEncrypted, true
      OUTGOING: mail.overit.it:25, alwaysSTARTTLS, passwordEncrypted, false
      OUTGOING: mail.overit.it:25, alwaysSTARTTLS, passwordEncrypted, false
      OUTGOING: mail.overit.it:25, alwaysSTARTTLS, passwordEncrypted, false

    account2:
      INCOMING: account2, , (none) Local Folders, plain, passwordCleartext

    account4:
      INCOMING: account4, , (im) prpl-gtalk, plain, 0

  Segnalazioni di arresto anomalo
    http://crash-stats.mozilla.com/report/index/bp-1ed8b835-93d7-442b-8b3a-2aa0b2141217 (17/12/2014)
    http://crash-stats.mozilla.com/report/index/bp-443ed992-3736-45dd-b9e5-70f552141217 (17/12/2014)
    http://crash-stats.mozilla.com/report/index/bp-22405fb9-8800-42bb-9d65-7b2af2141210 (10/12/2014)
    http://crash-stats.mozilla.com/report/index/bp-a2aa883e-300e-428e-913a-441672141205 (05/12/2014)
    http://crash-stats.mozilla.com/report/index/bp-12b8b37c-e550-40ec-b9b5-2f3b02141203 (03/12/2014)

  Estensioni
    ImportExportTools, 3.1, true, {3ed8cc52-86fc-4613-9026-c1ef969da4c3}
    Lightning, 3.3.2, true, {e2fda1a4-762b-4020-b5ad-a41df1933103}
    LookOut, 1.2.13, true, lookout@aron.rubin
    messagenotesplus, 1.4.0.8, true, messagenotesplus@mozilla.org
    Provider for Google Calendar, 1.0.3, true, {a62ef8ec-5fdc-40c2-873c-223b8a6925cc}
    QuickNote, 0.7.5, true, {C0CB8BA3-6C1B-47e8-A6AB-1FAB889562D9}
    Thunderbird Conversations, 2.8.1, true, gconversation@xulforum.org

  Preferenze importanti modificate

    Nome: Valore

      accessibility.browsewithcaret: true
      accessibility.typeaheadfind.flashBar: 0
      browser.cache.disk.capacity: 358400
      browser.cache.disk.smart_size_cached_value: 358400
      browser.cache.disk.smart_size.first_run: false
      browser.cache.disk.smart_size.use_old_max: false
      dom.max_chrome_script_run_time: 0
      extensions.lastAppVersion: 31.4.0
      font.name.monospace.el: Consolas
      font.name.monospace.tr: Consolas
      font.name.monospace.x-baltic: Consolas
      font.name.monospace.x-central-euro: Consolas
      font.name.monospace.x-cyrillic: Consolas
      font.name.monospace.x-unicode: Consolas
      font.name.monospace.x-western: Consolas
      font.name.sans-serif.el: Calibri
      font.name.sans-serif.tr: Calibri
      font.name.sans-serif.x-baltic: Calibri
      font.name.sans-serif.x-central-euro: Calibri
      font.name.sans-serif.x-cyrillic: Calibri
      font.name.sans-serif.x-unicode: Calibri
      font.name.sans-serif.x-western: Calibri
      font.name.serif.el: Cambria
      font.name.serif.tr: Cambria
      font.name.serif.x-baltic: Cambria
      font.name.serif.x-central-euro: Cambria
      font.name.serif.x-cyrillic: Cambria
      font.name.serif.x-unicode: Cambria
      font.name.serif.x-western: Cambria
      font.size.fixed.el: 14
      font.size.fixed.tr: 14
      font.size.fixed.x-baltic: 14
      font.size.fixed.x-central-euro: 14
      font.size.fixed.x-cyrillic: 14
      font.size.fixed.x-unicode: 14
      font.size.fixed.x-western: 14
      font.size.variable.el: 17
      font.size.variable.tr: 17
      font.size.variable.x-baltic: 17
      font.size.variable.x-central-euro: 17
      font.size.variable.x-cyrillic: 17
      font.size.variable.x-unicode: 17
      font.size.variable.x-western: 14
      mail.openMessageBehavior.version: 1
      mail.winsearch.enable: true
      mail.winsearch.firstRunDone: true
      mail.winsearch.global_reindex_time: 1331113395
      mailnews.database.global.datastore.id: 46963d85-d437-4707-aec9-bc9b5816302
      mailnews.database.global.views.conversation.columns: {"threadCol":{"visible":true,"ordinal":"1"},"flaggedCol":{"visible":true,"ordinal":"3"},"attachmentCol":{"visible":false…
      network.cookie.prefsMigrated: true
      places.database.lastMaintenance: 1332491385
      places.history.expiration.transient_current_max_pages: 104858
      plugin.importedState: true

  Grafica

      Descrizione scheda grafica: Mobile Intel(R) HD Graphics
      ID produttore: 0x8086
      ID dispositivo: 0x0116
      RAM scheda grafica: Unknown
      Driver scheda grafica: igdumd64 igd10umd64 igd10umd64 igdumdx32 igd10umd32 igd10umd32
      Versione driver: 8.840.7.0
      Data aggiornamento driver: 3-28-2011
      Direct2D attivo: Bloccato a causa della versione dei driver della scheda grafica.
      DirectWrite attivo: false (6.2.9200.16571)
      Parametri ClearType: Parametri ClearType non trovati
      Rendering WebGL: false
      Finestre con accelerazione GPU: 1/1 Direct3D 9

      AzureCanvasBackend: skia
      AzureSkiaAccelerated: 0
      AzureFallbackCanvasBackend: cairo
      AzureContentBackend: cairo

  JavaScript

  GC incrementale: 1

  Accessibilità

    Attivato: 0
    Impedisci accessibilità: 0

  Versioni librerie

      Versione minima prevista
      Versione in uso

      NSPR
      4.10.6
      4.10.6

      NSS
      3.16.2.3 Basic ECC
      3.16.2.3 Basic ECC

      NSS Util
      3.16.2.3
      3.16.2.3

      NSS SSL
      3.16.2.3 Basic ECC
      3.16.2.3 Basic ECC

      NSS S/MIME
      3.16.2.3 Basic ECC
      3.16.2.3 Basic ECC

**Comment by pianoslum** [comment]
This is #873 and should be fixed in the next version...

**Comment by protz** [comment]
@pianoslum thanks again for the triage.
