### ISSUE TITLE
No check spelling in quick reply

### ISSUE THREAD

**Issue by corvusd** [protz/GMail-Conversation-View#912]
Hello protz,

first of all, thank you for your great job and addon.

Then a few version back, this feature is dissapear in my text box area.

Is a actual bug or my profile problem?

My version: Ubuntu 14.04 Thunderbird 31.4.0  Thunderbird Conversations 2.8.1

Check the incompatiblities addon that your site. And not is my case.

Thanks in advance, greeting!

David Gámiz Jiménez

**Comment by pianoslum** [comment]
This is #850

**Comment by protz** [comment]
Thanks for cross-checking. i'll try to fix my patch and get it landed asap.
