### ISSUE TITLE
Attachments still not displayed after deleting global-messages-db.sqlite

### ISSUE THREAD

**Issue by kdarras** [protz/GMail-Conversation-View#913]
I am using Win 7, Thunderbird 31.4 and latest Conversations addon.

I closed Thunderbird, deleted the file global-messages-db.sqlite in my Profile folder (C:\Users\<Windows user name>\AppData\Roaming\Thunderbird\Profiles\<Profile name>\ ), and restarted Thunderbird. Twice.

All folders are up to date, I changed between accounts and messages and back, but still no attachment.
I have the problem with all messages, but once, after doing just that, I managed to get the attachments for a particular message. But now, there is no change anymore, and even that particular message does not show attachments.

PS: I was very happy with the addon and donated 5 USD before that :)
![attach](https://cloud.githubusercontent.com/assets/7696198/6131173/5b637a30-b14a-11e4-9104-7c8b26f59731.PNG)

**Comment by laclaro** [comment]
Hi,

same problem here. Even the addon display-all-body-parts does not help. Some attachments (not all of them!) are not displayed. Because I use Thunderbird in an enterprise environment, this issue makes "Conversations" unusable for me. I would really like to use it.

Best regards,
Henning

**Comment by pianoslum** [comment]
See #841 ; enabling 'Select this folder for offline use' could help...

**Comment by kdarras** [comment]
Thanks, it worked for me!

**Comment by protz** [comment]
Closing to avoid duplicates. Thanks @pianoslum for the triaging!
