### ISSUE TITLE
Conversations popup window too big

### ISSUE THREAD

**Issue by ptav** [protz/GMail-Conversation-View#915]
On windows 8.1 the popup conversation window (which appears when user double-clicks message in message list) is too long disappearning above and below the screen. When the task bar is permanently visible the close/minimize/maximize buttons are pushed outside the screen and are unaccessible

Windows 8.1
Thunderbird 31.4.0
Conversations  2.8.1

Thanks

**Comment by pianoslum** [comment]
What do you mean by "popup" - doesn't it open a new tab?
Could you provide a screenshot?

**Comment by protz** [comment]
This was fixed in 09bcfd69d5ab609c169865729b0e6602a03efff4 and will be in the next version. Thanks for reporting!

**Comment by ptav** [comment]
Thanks for the update. I'm indeed using it in a Surface pro 2 which has 
a narrower screen than most
