### ISSUE TITLE
Display of recipients overlays buttons when conversation-area is to small

### ISSUE THREAD

**Issue by anoderay** [protz/GMail-Conversation-View#918]
The senders and recipients information sometimes overlays the buttons "Show Detail", ""Answer all" etc. and pushes the buttons to the right when e.g. using a three-column view. See attached screenshot for example. Contact me, if you need further details.
![screenshot_1](https://cloud.githubusercontent.com/assets/11176096/6349540/004a15e0-bc2c-11e4-8775-8fa4c16db809.png)

**Comment by pianoslum** [comment]
This is #873 and should be fixed in the next version...

**Comment by protz** [comment]
Yep, correct. Closing this so that it's not a duplicate.
