### ISSUE TITLE
Junk meta-folder missing entirely

### ISSUE THREAD

**Issue by sparr** [protz/GMail-Conversation-View#919]
I was concerned when enabling this add-on caused the Junk folder for each of my accounts to disappear. From reading other comments and issues here I believe that I should be seeing a top level Junk folder, similar to my top level Inbox, Drafts, Sent, Archives, Trash, Outbox, my account top level folders, and my local folders folder. However, I am not seeing it. Junk is entirely missing. I have to disable the add-on to find any email in my junk folders.

I am running version 2.8.1

**Comment by pianoslum** [comment]
Seems to be the same as #902 But I have no idea...

**Comment by protz** [comment]
I'm closing this and trying to investigate in #902. Please followup there, thanks! :)
