### ISSUE TITLE
Question: Upstream Merge?

### ISSUE THREAD

**Issue by yoshimo** [protz/GMail-Conversation-View#921]
Since the Q&A external website is out of order, the question comes here.

Are there any plans to get this new ui and features into the mainline Thunderbird one day?

**Comment by pianoslum** [comment]
I guess you have to ask the Thunderbird folks... but I think there are no specific plans.

**Comment by protz** [comment]
No, there were some plans at some point, but the move was never made. I believe there's just too much engineering effort to polish and fix all the small little features that this addon does not implement correctly. Plus, there's the issue of performance which is a showstopper in most cases...

(I wish it had been integrated, though!) :)
