### ISSUE TITLE
Wrong conversation on reply

### ISSUE THREAD

**Issue by toblerone1963** [protz/GMail-Conversation-View#922]
On the last Thunderbird (31.5.0), whenever I want to use Conversation reply or reply all, it use a different conversation (always the same). 
![A conversation I want to reply](https://cloud.githubusercontent.com/assets/5781292/6459532/d7111dc2-c18f-11e4-8a36-87f9ae254937.png)
![Another conversation… -_-"](https://cloud.githubusercontent.com/assets/5781292/6459540/eb9bbc16-c18f-11e4-92a5-58c45e3ae5f0.png)

Thanks for all by the way !

**Comment by pianoslum** [comment]
Is this only since the latest Thunderbird update?
And what do you mean by "it use a different conversation (always the same). " Is the recipient's address wrong? Or the cited text?

Further infos would be good (operating system, etc.)

**Comment by toblerone1963** [comment]
I only notice since the latest update.

How to say it differently… When I want to reply, it doesn't reply to the right message, but to another one (cited text,  recipient's and sender's addresses…).

I'm on mac os 10.10.2, Thunderbird 31.5.0, Conversation 2.8.1. I have three boxes.

**Comment by pianoslum** [comment]
Sorry, I can not reproduce this. Is it only in 'Quick reply'-mode?
Maybe try to reinstall Conversations?

**Comment by toblerone1963** [comment]
okay… it's working… sorry for the trouble  -_-"

**Comment by protz** [comment]
I've had reports of this but I've never seen it happen myself. If you find better steps to reproduce, please do reopen this. Thanks!

Jonathan
