### ISSUE TITLE
reply in text mode

### ISSUE THREAD

**Issue by laclaro** [protz/GMail-Conversation-View#923]
Hi,

I do not use HTML in my e-mail messages. However, "Conversations" does not honor this thunderbird-setting and opens a HTML-editor if I use the reply button. Inline replies on the other hand do honor the thunderbird setting and do not create HTML-messages.

Best regards,
henning

**Comment by protz** [comment]
Hi,

While the HTML editor always shows up, the actual message being sent will be plaintext, unless you use some feature that requires HTML (e.g. images). So in that sense, we do honor the pref, it's just that to cut complexity, Conversations doesn't have two editors just like Thunderbird does. Given that I'm already unable to fix bugs and prevent the addon from being broken, I can't really afford to have the same level of complexity as Thunderbird :)

Thanks,

Jonathan
