### ISSUE TITLE
How to to a top post (above old quoted text)?

### ISSUE THREAD

**Issue by guettli** [protz/GMail-Conversation-View#925]
How to to a top post (above old quoted text)?

Is there a way to configure the position of the cursor if I do a reply?

AFAIK the netiquette says you should put your reply text below the old (and quoted) text.

But we live in the 21 century. Only few people know the netiquette. AFAIK there is no rewrite of it, but just look at the practice: People do put their text above the old. If most people act agains the rule, it is time to discuss the rules again.

**Comment by protz** [comment]
I think the FAQ item "I want the reply to above/below quoted text" might be what you're looking for. See https://github.com/protz/GMail-Conversation-View/wiki/faq

Cheers,

Jonathan

**Comment by guettli** [comment]
I was blind. Sorry. Thank you for the answer.
