### ISSUE TITLE
pdf.js viewer is currently broken

### ISSUE THREAD

**Issue by protz** [protz/GMail-Conversation-View#928]
Consider getting rid of it?

**Comment by CraigAD** [comment]
It is nice when "preview" is working.  Until it is, I still have "open."  My vote is to keep it, but lower its priority until most other issues are resolved.

--201503221846-master on EarlyBird

**Comment by pianoslum** [comment]
The error is "Timestamp: 29.03.2015 16:28:08
Error: Error: Permission denied to access property 'reduce'
Source File: resource://conversations/content/pdfviewer/viewer.js
Line: 135"

In the code you did some kind of a workaround to get rid of that error; maybe now Thunderbird's security policy is stricter...
I don't know anything about this access-rights. If it was too complicated to fix it, I think it would be ok to drop the feature...

**Comment by protz** [comment]
Quoting https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XPCOM/Language_bindings/XPConnect/XPConnect_wrappers

> Note that a previous version of the current page recommended using __exposedProps__ to expose objects from chrome to content. This is now deprecated and we are in the process of removing support for it. If you need to make objects or functions defined in chrome code accessible to content, use Components.utils.cloneInto or Components.utils.exportFunction.

This constant breakage is exhausting.

**Comment by protz** [comment]
In all fairness, for once, the documentation was decent and it took me less than 10 minutes to fix it. If only all bugs were like this!

**Comment by protz** [comment]
Please note that I didn't refresh the version of pdf.js that we bundle, nor did I improve in any way the viewer. If anyone feels like doing so, I'd gladly accept a pull request!
