### ISSUE TITLE
Message window opens too large and is normally not re-sizable.

### ISSUE THREAD

**Issue by Gwalior-84** [protz/GMail-Conversation-View#935]
An issue that occurs with this add-on (Thunderbird Conversations 2.8.1):

Whenever I double-click on a message, it opens in a new window, which is what I want it to do. The problem is that the opened message window is about 40% as wide as my main laptop display, and about 150% as high.  It is too tall for either of my two displays (1366x768 on the laptop, 1600x1200 on my external display).

Sometimes the window that opens can be resized, other times not!  I can reproduce the following two cases:

1.  If I double-click on the email in the thread pane, the opened window is too large, with the top 20% of the message off the top of my screen.  The message window cannot be maximised or resized.  I can manually move the window around with a tedious combination of keystrokes / mouse clicks.  TB forgets these window settings, and every time I open a message in a new windows, I get the same problem.

2.  If I open the message window by scrolling to the bottom of the message in the message pane and clicking on the 'in a new window' button at the bottom left, then the opened message window is resizable.  Not only that, but TB remembers the opened window size and location for subsequent openings.  This is the desired behaviour! 

I am using a new computer Win 8.1, TB 31.5.0, Default theme.

**Comment by protz** [comment]
Hi,

This is a known issue that will be fixed in the next release. In the meanwhile, a workaround is to set your reading preferences to open these messages in a new tab.

Thanks for reporting!

Jonathan

**Comment by Gwalior-84** [comment]
Thanks for responding Jonathan, and by the way, in every other respect,
this is a great add-on.  Keep up the good work!
