### ISSUE TITLE
Quick reply strips away consecutive whitespace when inserting signature

### ISSUE THREAD

**Issue by jmickelin** [protz/GMail-Conversation-View#936]
Steps to reproduce:

1. Configure an account to have a signature as follows, using whitespace for alignment:

  ````
Foo McBar                     Baz university
                                  Qux department
Tel: 867-5309     PGP id: 0xDEADBEEFABCDEFAB
  ````
2. Reply to a message using the "quick-reply" box in the conversation view.

Expected behaviour: The signature should be inserted verbatim, like in the built-in message composer window.
Actual behaviour: The signature is stripped from whitespace:
```
Foo McBar Baz university
Qux department
Tel: 867-5309 PGP id: 0xDEADBEEFABCDEFAB
```

**Comment by protz** [comment]
Thanks, I'll look into it when I get a chance.

**Comment by protz** [comment]
Hi,

So that's just the way messages are viewed using Conversations. Conversations never uses a monospace font for your messages, meaning that even though the message does contain the right whitespace in your signature, it's just ignored when displayed. You can tweak this by choosing to use a monospace font when displaying messages in the addon's options, or by hitting "more > view using classic reader".

Cheers,

Jonathan

**Comment by jmickelin** [comment]
I don't think that's the case. I just tried it as follows:

1. I sent a message to myself from the classic composer.

2. I replied to this message from the quick compose window (the signature was then displayed without whitespace in the compose window).

3. I replied again from the quick compose window, this time reinserting the missing whitespace by hand.

In both the classic reader and the conversation view, messages 1 and 3 are displayed correctly, and 2 is displayed without the whitespace.

I use a monospace font for both the classic reader and the addon.

**Comment by protz** [comment]
I tried steps 1. and 2. and the right whitespace is still shown in the quick compose area at step 2.

Do you have unusual settings / other addons / are you fetching your signature from a file... ?

**Comment by jmickelin** [comment]
Huh, this is strange. I have one other addon installed, namely Enigmail. That does seem to be what's causing the problem: I created a new profile and installed just Thunderbird Conversations, and found that everything works as on your machine. But as soon as I install Enigmail, I get the bug. The problem persists if I disable or remove Enigmail.
