### ISSUE TITLE
Colors from GTK Theme

### ISSUE THREAD

**Issue by balasankarc** [protz/GMail-Conversation-View#938]
Hi,
I am using Icedove 31.5.0 on Debian Sid. I am using a dark theme (DeLorean-Dark) for my GTK. The Thunderbird Conversations addon doesn't respect the color scheme. See attachment. I also tried building from the git repo, but it can't be installed as it is not compatible with my Icedove version.
![screenshot from 2015-04-05 11 40 17](https://cloud.githubusercontent.com/assets/2379271/6995982/e8afe9c4-db88-11e4-8adf-867096d36ac3.png)

I manually changed the colors of the text window from Icedove preferences, but don't know what to do about the borders and other panes.

**Comment by protz** [comment]
This has been fixed in the next version, which is available as an xpi here http://jonathan.xulforum.org/files/gcv-nightlies/ and is currently compatible with Thunderbird 38 onwards (currently in beta).

Thanks,

Jonathan
