### ISSUE TITLE
Mixed threaded in "All Mail" folder

### ISSUE THREAD

**Issue by guoyunhebrave** [protz/GMail-Conversation-View#939]
![thunderbird wrong thread](https://cloud.githubusercontent.com/assets/5836790/7004246/2391a1c0-dc71-11e4-97db-045a99da94f3.png)

In this screenshot, I receive an email that some one want to buy my bike. But another mail mixed in this thread, which is the reply of ticket booking a month ago.

Only in "All Mail" folder, other folders are perfect when displaying thread.

When I received a new mail, I archive it. Then I check it in "All Mail" folder of my Gmail account. I found there are always some old, unrelated mails in this thread. This situation happens every time I receive an email.

This is strange.

**Comment by guoyunhebrave** [comment]
Update:

I have tried to uninstall and reinstall the extension, but this problem still exists.

I have about 5700 mails in "All Mail". Only mails received after installed Thunderbird Conversition have this problem, old mails display thread perfectly.

**Comment by msprotz** [comment]
I think that's the first issue covered at https://github.com/protz/GMail-Conversation-View/wiki/faq

Thanks,

Jonathan

**Comment by guoyunhebrave** [comment]
I have read https://bugzilla.mozilla.org/show_bug.cgi?id=646225

It is a bug reported in 2011. And nobody are following it? Just want to know how can we fix it, what can I help.

**Comment by protz** [comment]
Yes, I don't think anyone has both the skills and the time to fix this, now...

**Comment by protz** [comment]
That's kind of unfortunate, and I don't think it's *that* hard to fix; probably the hardest part will be writing a test that accurately triggers the issue. If you're interested, my last comment on the bug describes what's needed to fix it!

Cheers,

Jonathan

**Comment by guoyunhebrave** [comment]
This is hard for me. I even don't know where to get the source code of Thunderbird. It is better if you can tell me the clone url.

**Comment by guoyunhebrave** [comment]
**Rebuilding message index database** can make existing email threads display correctly.
https://support.mozilla.org/en-US/kb/rebuilding-global-database
But new mails will still go to wrong threads. You have to frequently rebuild database. So this is not a solution.
