### ISSUE TITLE
"undefined" for from/to/cc w/ TB 38.0b1 and conversations 20150329

### ISSUE THREAD

**Issue by zzzeek** [protz/GMail-Conversation-View#940]
probably some regression due to changes in TB, clicking "show details" comes up with "undefined" for most email addresses.   See screenshot at: http://i.imgur.com/ZCKf8j3.png

**Comment by zzzeek** [comment]
platform is OSX yosemite

**Comment by protz** [comment]
Which version of Thunderbird and Conversations?

**Comment by zzzeek** [comment]
in the title...  [TB 38.0b1](https://www.mozilla.org/en-US/thunderbird/38.0beta/releasenotes/) and the nightly of conversations 20150329 from http://jonathan.xulforum.org/files/gcv-nightlies/201503292045-master.xpi.

**Comment by protz** [comment]
I think that nightly is broken, I need to refresh it. I forgot to do it 
after fixing that bug.

**Comment by protz** [comment]
Thanks for reporting!

**Comment by zzzeek** [comment]
conversations is great!

**Comment by protz** [comment]
http://jonathan.xulforum.org/files/gcv-nightlies/ uploaded a new release, let me know if that works for you

**Comment by zzzeek** [comment]
works, thank you!   i have more issues to report if you dont mind...

**Comment by protz** [comment]
go ahead!

~ jonathan
