### ISSUE TITLE
Stopped working with new Thunderbird upgrade

### ISSUE THREAD

**Issue by danielc1234** [protz/GMail-Conversation-View#941]
Hi,

I just updated Thunderbird and now my Conversations will not work anymore. It sorts the folders correctly, but will not display the contents of any emails. It will just loading... and then nothing.
Anything I can do to get it working again? Sucks not being able to use it.

Thanks
Dan

**Comment by protz** [comment]
If you're on beta you probably need the latest version from http://jonathan.xulforum.org/files/gcv-nightlies/

Thanks,

Jonathan
