### ISSUE TITLE
clicking on a message to open in a separate window produces a window that is not resizeable

### ISSUE THREAD

**Issue by zzzeek** [protz/GMail-Conversation-View#942]
TB 38.0b1, conversations nightly 201504080726-master.xpi, OSX Yosemite

if I read a thread in its own window, such as by double clicking or pressing return on any message in a mailbox, the opened window shows conversations but the window overall is not resizable (and also stretches the vertical width of the screen).   with conversations turned off, the window has a bottom bar that allows resizing (and is also a status bar).

compare conversations: http://i.imgur.com/cgF6hV7.png
to plain: http://i.imgur.com/WHgwGNY.png

**Comment by msprotz** [comment]
Thanks for reporting. This is the same thing as #914 and is likely to require quite a fair bit of work.

**Comment by protz** [comment]
Thanks for reporting. This is the same thing as #914 and is likely to require quite a fair bit of work.

**Comment by protz** [comment]
For the specific issue about resizing, thinking about it, I'm actually
surprised that the window can't be resized. The dev build you downloaded is
actually just a zip file. Can you try editing the file modules/misc.js to
change line 291 from

      window.open(aUrl, "conversations", "chrome,width=640,height="+height);

to

      window.open(aUrl, "conversations",
"chrome,resizable,width=640,height="+height);

see if that helps?

On Wed, Apr 8, 2015 at 8:39 AM, Jonathan Protzenko <notifications@github.com

**Comment by zzzeek** [comment]
doesn't seem to have an effect :|

**Comment by protz** [comment]
Ok... (I assume you reinstalled the addon and restarted Thunderbird 
after modifying the .xpi?). Then it actually is a non-trivial amount of 
work to make this work :)

**Comment by zzzeek** [comment]
Yeah I uninstalled the current, then installed this, then restarted.  But I don't know the quirks of TB and plugins, i can try going through and making sure I got it all correct.

**Comment by zzzeek** [comment]
OK i checked "openMessageBehavior" and that was the issue, mine comes up with "0", so this works:

    case 0:
      window.open(aUrl, "_blank", "chrome,resizable,width=640,height="+height);
      break;
    case 1:
      window.open(aUrl, "conversations", "chrome,resizable,width=640,height="+ height);
      break;

not sure what 0 and 1 mean here?

**Comment by zzzeek** [comment]
OK, means "new window" or "current window".

**Comment by protz** [comment]
Super. I just pushed a fix this will be in the next "dev build". Thanks!
