### ISSUE TITLE
Spellchecker Bug

### ISSUE THREAD

**Issue by uksitebuilder** [protz/GMail-Conversation-View#945]
In quick reply, spellchecker underlines incorrectly spelt words fine, but right-clicking those incorrectly spelt words does not bring up recommended corrections.

Likewise when sending the quick reply, the spell-checker does not popup as it does in normal Thunderbird working.

**Comment by protz** [comment]
This is fixed if you use Thunderbird 38 and one build from http://jonathan.xulforum.org/files/gcv-nightlies/
