### ISSUE TITLE
Can't read message on latest master

### ISSUE THREAD

**Issue by pianoslum** [protz/GMail-Conversation-View#946]
Just noticed: Click on a message (offline) - see following error, message loads forever:

Timestamp: 14.04.2015 01:01:56
Error: 2015-04-14 01:01:56	Conversations.Conversation	ERROR	ReferenceError: sanitize is not defined

Source File: resource:///modules/gloda/log4moz.js
Line: 693

2015-04-14 01:01:56	Conversations	DEBUG	
_ContactMixIn_toInlineHtml@resource://conversations/modules/contact.js:153:7
Message.prototype.toTmplData@resource://conversations/modules/message.js:517:28
_Conversation_outputMessages@resource://conversations/modules/conversation.js:994:21
_Conversation_getReady/<@resource://conversations/modules/conversation.js:632:7
_Conversation_signal@resource://conversations/modules/conversation.js:107:7
_Conversation_onQueryCompleted_bug547088@resource://conversations/modules/conversation.js:618:9

**Comment by protz** [comment]
git submodule update?

**Comment by pianoslum** [comment]
You're right, sorry!
