### ISSUE TITLE
Error after uninstalling Conversations

### ISSUE THREAD

**Issue by pianoslum** [protz/GMail-Conversation-View#947]
STB:

* install Conversations
* uninstall Conversations
* In the debug window is the following error:

Timestamp: 14.04.2015 01:03:29
Error: NS_ERROR_NOT_AVAILABLE: Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsIXPCComponents_Utils.import]
Source File: resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///home/paul/.thunderbird-trunk/550eddv3.deb/extensions/gconversation@xulforum.org.xpi!/bootstrap.js
Line: 148

**Comment by protz** [comment]
It's most likely the observer that watches for new windows that's not properly unregistered...
