### ISSUE TITLE
Double clicking on conversations that have image attachments crashes Thunderbird

### ISSUE THREAD

**Issue by berdario** [protz/GMail-Conversation-View#951]
This happens when clicking on any column of the messages views (not the mail content view)

When this extension is disabled there's no crash

**Comment by protz** [comment]
If Thunderbird crashes, it's a Thunderbird issue. Can you file a bug at http://bugzilla.mozilla.org? They will need your crash id; you can find it by running `Tools > Error Console`, then typing: `top.opener.openTab("contentTab", { contentPage: "about:crashes" })` and hitting enter.

Thanks,

Jonathan

**Comment by berdario** [comment]
[reported it](https://bugzilla.mozilla.org/show_bug.cgi?id=1158033)

**Comment by protz** [comment]
Thanks!
