### ISSUE TITLE
event invite's accept button sometime doesn't do anything

### ISSUE THREAD

**Issue by YoogleMarcus** [protz/GMail-Conversation-View#955]
When I get an invite, with the usual cancel, tentative, and accept buttons, clicking on those buttons while in conversation view doesn't do anything, and at other times it is very slow. When I go to classic view, I get an immediate feedback ("This message ... already processed.").

Is this a bug in SW or my misconfiguration?

**Comment by protz** [comment]
I don't know -- I don't use lightning. I'm inclined to believe you and assign this as a bug. If you have the skills, any help to fix this would be most welcome.

**Comment by protz** [comment]
I'm closing this one in favor of #961 since both seem to be the same underlying issue.
