### ISSUE TITLE
Compatibility issue with TB 31.6.0.

### ISSUE THREAD

**Issue by Michael-E-Rose** [protz/GMail-Conversation-View#957]
I downloaded Thunderbird Conversations 2.9.0 from [addons.mozilla.org](https://addons.mozilla.org/en-us/thunderbird/addon/gmail-conversation-view/) where it says that "The latest version is compatible with Thunderbird 31+ only (see below for details)."

However, I just wanted to install the addon on my Thunderbird 31.6.0., running on a Ubuntu 14.04. But all I saw is this error message, stating the addon is not compatible with my TB version:
![screenshot from 2015-05-08 12 12 37](https://cloud.githubusercontent.com/assets/7095926/7534552/dec696bc-f57b-11e4-95e8-72a78aca532c.png)

Despite my limited knowledge of Thunderbird, I suspect a bug around here.

**Comment by pianoslum** [comment]
The description is wrong; you can only use version 2.9 the latest Thunderbird. Below is the right description: "Works with Thunderbird 38.0a1 - 40.0a1"

**Comment by Michael-E-Rose** [comment]
In this case, one could change the description. I saw the "see below" hint, but I was looking more below than just below the download button.

I also wonder why you optimize version 38.0a1- the current release for both Linux and Windows systems is 31.6.0., isn't it? Thunderbird 38.0a1 can't be used by many people, I believe.

**Comment by protz** [comment]
addons.mozilla.org does not show you a version of Conversations based on
your version of Thunderbird -- that's unfortunate. I had a choice
between either submitting the new version (2.9) after Thunderbird 38 was
released, and risking users on 38 installing an incompatible version,
or, I could submit the 2.9 version right before 38 was released, and
having a short period of time where users have to go to "versions" to
find the older versions.

38 has been delayed, so of course the short period of time is going to
last for a little while longer now...

I'll change the text.

~ jonathan

T

**Comment by Michael-E-Rose** [comment]
Ah, so my misunderstanding is accidental. In this case we can safely close the issue. Thanks for changing the text anyway!
