### ISSUE TITLE
gallery view not working with 38 beta

### ISSUE THREAD

**Issue by Chris115v** [protz/GMail-Conversation-View#959]
Clicking on gallery view link just gets a new tab that is totally blank and light blue colored. Error console shows this error:

Timestamp: 5/16/15, 10:14:11 AM
Error: TypeError: $(...).tmpl is not a function
Source File: chrome://conversations/content/gallery/js/gallery.js
Line: 103

I'm not much of a js or jquery person. Doesn't look like that line has changed recently. Something elsewhere changed to make jquery .tmpl() not available here?

**Comment by Chris115v** [comment]
Hmmm. line 10 in content/gallery/index.html, jquery.tmpl seems to be missing. Looks like it was replaced with Handlebars, but gallery code didn't get integrated with it?

**Comment by Chris115v** [comment]
If I put jquery.tmpl back in the package, and fix the path in content/gallery/index.html by removing the .., then gallery view works again. So looks like Handlebars integration is a work in progress?

I looked a little at the Handlebars integration, but would need more time to figure out what calls need to change.

**Comment by protz** [comment]
No it should be replaced with proper handlebars support. Can you submit
a patch to fix that? It should be pretty easy if you copy what's done in
stub.xhtml I believe.

Thanks,

~ jonathan

**Comment by protz** [comment]
(Very little time available right now, unfortunately, so I won't be able to push a fix soon.)

**Comment by Chris115v** [comment]
submitted a pull request for the stub.xhtml file in gallery. Works for me in place of index.html.

**Comment by protz** [comment]
Thanks for submitting two pull requests, but fixing this required definitely more work than just rewriting `${` into `{{`. I'm thus a little bit confused as to why you claimed earlier that it works for you.

In any case, the fix is in 7d46bdd so I'm going to close your two pull requests.

**Comment by Chris115v** [comment]
Oh well, it did seem too simple. Maybe I didn't properly pull out the old jquery tmpl and it was still working. I'm very new to this whole extension business. Thanks for fixing.
