### ISSUE TITLE
Feature Request: Single-click to Reply (button or link)

### ISSUE THREAD

**Issue by DaveJarvis** [protz/GMail-Conversation-View#965]
The following image shows an example message from my inbox:

![reply](https://cloud.githubusercontent.com/assets/2131950/7971301/a2028d58-09f8-11e5-80fc-5f8983035387.png)

There is no obvious way to reply to the message (in a new window) with a single click. Here are the options that I found:

- Scroll down until the reply field is visible (slow for long message content), then click *reply in a new window*.
- Click *more >> reply* (two clicks, and the option is hidden, making it a hunting game).
- Right-click on the message, select *Reply to Sender only* (two clicks, mouse movement, hidden context menu).
- Press `Ctrl+r` (fastest way, but without a visual indicator).

Please add a label to the icon bar for the following:

- Reply to all
- Reply to sender

For example:

![reply-label](https://cloud.githubusercontent.com/assets/2131950/7971495/eca27912-09f9-11e5-82ab-50c8832141e8.png)

**Comment by protz** [comment]
Hi,

Thanks for the feedback. There's a tradeoff here between UI clutter / convenience / sane choice of defaults. The default for reply vs. reply all has been rehashed several times, and any choice will make half the users unhappy, so I'm not willing to revisit this. Adding any more buttons in the UI is also not an option, this will clutter the interface which is already pretty dense.

I think two clicks (more > reply) is an acceptable penalty that doesn't warrant i) more code and ii) a more complex UI.

Thanks,

Jonathan
