### ISSUE TITLE
With TB 38.0.1 if extension is activated, can't view emails...

### ISSUE THREAD

**Issue by ArfyFR** [protz/GMail-Conversation-View#968]
I updated to 38.0.1 and had to desactivate extensions one by one.
After desactivating TB Conversation and restarting TB, all went OK

**Comment by protz** [comment]
You need to update the addon as well, then restart Thunderbird once more.

**Comment by ArfyFR** [comment]
Ok thanks it worked.
What was strange: While updating TB, it didn't ask to update it.

And neither after several TB restarts.

Envoyé à partir de mon Windows Phone
________________________________
De : Jonathan Protzenko<mailto:notifications@github.com>
Envoyé : ‎13/‎06/‎2015 08:11
À : protz/GMail-Conversation-View<mailto:GMail-Conversation-View@noreply.github.com>
Cc : ArfyFR<mailto:borschneck@hotmail.com>
Objet : Re: [GMail-Conversation-View] With TB 38.0.1 if extension is activated, can't view emails... (#968)

You need to update the addon as well, then restart Thunderbird once more.

---

**Comment by ArfyFR** [comment]
But I had to disable it again, no more able to delete a mail...
