### ISSUE TITLE
With TB 38.0.1 if extension is activated, can't delete my emails

### ISSUE THREAD

**Issue by ArfyFR** [protz/GMail-Conversation-View#969]
Hi back,

This time extension is up to date (2.9.0) but if it is activated, the "delete" does nothing...
If I disable the extension, all is ok.

Arfy

**Comment by protz** [comment]
Which "delete"?

~ jonathan

**Comment by ArfyFR** [comment]
![deleteconversdationproblem](https://cloud.githubusercontent.com/assets/3436322/8145597/29f1db84-120e-11e5-8030-90d5f35353b7.jpg)

By disabling the extension I am able to delete an email with the "Supprimer" (in french) button
Is enable, on "your" button, no, cf image

**Comment by protz** [comment]
Yeah it's a known bug, I've fixed it already, I just need to issue a new
release. Just grab the latest snapshot named 2.9+ at
http://jonathan.xulforum.org/files/gcv-nightlies/ in the meanwhile.

Thanks,

~ jonathan
