### ISSUE TITLE
TB38 + Conv2.9.0: Using an `&` in a folder name prevents viewing messages

### ISSUE THREAD

**Issue by blerner** [protz/GMail-Conversation-View#970]
I have a folder named "Foo & bar", say, and an unread message is filtered into it.  When I press the 'n' key to view it, conversations gets stuck at the "Loading" interstitial page.  The error console says "error: malformed `>Foo & bar</li`" somewhere in stub.xhtml -- I'm guessing line 872 or line 1109, which don't seem to html-escape their templated data.

**Comment by protz** [comment]
Good catch, thanks!

**Comment by protz** [comment]
I've uploaded a new version btw https://addons.mozilla.org/en-US/developers/addon/gmail-conversation-view/versions/1710676

Hope that helps!

**Comment by liujed** [comment]
protz, you mean to link to ![v2.9.1](https://addons.mozilla.org/en-US/thunderbird/addon/gmail-conversation-view/versions/2.9.1) ? The link you gave above appears to be private.

**Comment by protz** [comment]
Yeah sorry that is what I meant, yes.

**Comment by blerner** [comment]
That does fix it, thanks :)
