### ISSUE TITLE
New items in a thread do not mark the thread as unread.

### ISSUE THREAD

**Issue by lancecopeland** [protz/GMail-Conversation-View#972]
I apologize if this has been answered.  All the posts are not "quite" actually what I am asking.
Without clicking on anything in the Thunderbird window when a new message arrives within a thread the thread is NOT marked as unread again (bolded)  Therefore I do not know when a thread has been replied to unless I see it come up on my phone first.

**Comment by protz** [comment]
If you're talking about the thread pane (i.e. the "list of messages" in your current folder), this is controlled by Thunderbird, and Thunderbird underlines the thread when *some*, but not all of the messages in the thread, are unread.

Let me know if that answers your question, or please close the issue otherwise.

Thanks!

**Comment by protz** [comment]
I'm assuming that this answers the original bug report.

**Comment by groovenectar** [comment]
I'm running into this as well.. Threads with a new unread message appear the same as read messages in the list, and it's hard to tell that there's new email...

But after seeing your answer, I do notice the underline on the date column! That should help, and I did just now notice a few emails I'd not seen yet..

I thought it would be neat to have a collapsed thread appear bold again if any of its contents are unread, but knowing about the underline will be really helpful, thanks

**Comment by qazip** [comment]
@protz, would you be so kind as to tell me what I should add to my userChrome.css as to change this behaviour? I would like to change the color of the unread conversations. The underline is barely visible to me.
