### ISSUE TITLE
Delete-conversation button does nothing

### ISSUE THREAD

**Issue by liujed** [protz/GMail-Conversation-View#973]
When the delete-conversation button in the message-display header is clicked, a type error is logged on the console: "pending[Symbol.iterator] is not a function" at msgHdrUtils.js:270.

**Comment by protz** [comment]
I've just submitted version 2.9.1 which is pending review on addons.mozilla.org; in the meanwhile, use the latest version marked as "2.9+" at http://jonathan.xulforum.org/files/gcv-nightlies/

Thanks,

jonathan
