### ISSUE TITLE
[TB 38.0.1] Messages are not displayed

### ISSUE THREAD

**Issue by EpicWolverine** [protz/GMail-Conversation-View#974]
Since updating to Thunderbird 38.0.1 (using Thunderbird Conversations 2.8.1), messages are no longer displayed.
![Image of messages not displaying](http://i.imgur.com/aJAaMkt.png)
The message is not empty however, as messages are displayed normally with the add-on disabled and the contents of the message are summarized correctly when it is collapsed.
![Image of collapsed message](http://i.imgur.com/AX1wMKP.png)
Please look into this as it makes Thunderbird unusable with the add-on enabled, but I'd hate to use Thunderbird without it. I can try to provide any more information (such as log messages) as needed.

**Comment by protz** [comment]
Can you restart thunderbird?

**Comment by protz** [comment]
Also, you need to update Conversations as well. 2.8.1 is *not* compatible with Thunderbird 38, you need 2.9.1 for that (see https://addons.mozilla.org/en-US/developers/addon/gmail-conversation-view/versions/1710676)

**Comment by EpicWolverine** [comment]
Of course it was that simple. Yes, I just needed to force Thunderbird to check for add-on updates and restart. I had (foolishly) assumed it would do so automatically. Thanks anyway! Your add-on rocks.
