### ISSUE TITLE
Unified Inbox showing Sent Messages also

### ISSUE THREAD

**Issue by harshasrisri** [protz/GMail-Conversation-View#976]
Hi, I'm using Thunderbird 38 on Manjaro Linux. Right after updating, the addon did not load any conversations in conversation view. I removed and added it again which solved the problem.

Now, the unified Inbox is showing all my inboxes correctly, in addition, the sent mail from all the accounts are being displayed as well. This doesn't happen if I view an individual inbox alone.

**Comment by protz** [comment]
Yeah I think both of these are in the faq. The first one is Thunderbird upgrading to 38 without upgrading Conversations at the same time. The second one can be solved by hitting View > Folders > All or reverting the customizations (right-click on unified inbox, hit properties, choose, and then pick which folders you wish to see in your unified inbox).
