### ISSUE TITLE
"Delete this conversation" not working.

### ISSUE THREAD

**Issue by drguildo** [protz/GMail-Conversation-View#977]
As the title says, when I click the "Delete this conversation" button, nothing happens. I get this in the error console:

    Timestamp: Sat 20/06/2015 01:12:33 PM
    Error: TypeError: pending[Symbol.iterator] is not a function
    Source File: resource://conversations/modules/stdlib/msgHdrUtils.js
    Line: 270

The normal Thunderbird delete operations work fine.

**Comment by protz** [comment]
https://addons.mozilla.org/En-us/thunderbird/addon/gmail-conversation-view/ has 2.9.1 which was just released. It fixes this issue.

Thanks,

Jonathan
