### ISSUE TITLE
Enable 'Conversation view' as part of setup assistant

### ISSUE THREAD

**Issue by patricktokeeffe** [protz/GMail-Conversation-View#979]
I couldn't figure out why this plugin (v2.8.1) wasn't working... enable, disable, uninstall, install. Solved it after noticing `View > Conversation View` wasn't selected. That's a good option for the setup assistant to auto enable.

**Comment by protz** [comment]
This is a menu button that's installed by the addon, and it's on by default, so the issue has got to be something else. Either you installed this addon a while ago and left the button disabled, or you're experiencing the issue described in the FAQ (upgrade issue)...

**Comment by patricktokeeffe** [comment]
I figure it was me changing things and forgetting about them. Does the menu button being created make it too difficult to add to that list of recommended settings?
