### ISSUE TITLE
PGP/MIME attachments do not show in Conversations

### ISSUE THREAD

**Issue by Natanji** [protz/GMail-Conversation-View#980]
I can perfectly reproduce this: when I send a message to e.g. myself that has encrypted PGP/MIME attachments (via Enigmail), then those attachments don't show up in Conversations. In the classic view, they do show up without a problem.

**Comment by JanKraljic** [comment]
I can confirm same isssue

**Comment by shaded2** [comment]
confirmed issue as well.

**Comment by protz** [comment]
http://jonathan.xulforum.org/files/gcv-nightlies/20150708-master.xpi has the fix

**Comment by Henni** [comment]
I'm currently on version 2.10.2 and the issue still occurs.
Enabling "I love attachments" in the add-on preferences fixes this issue.
