### ISSUE TITLE
Quick reply buttons don't conform to GTK theme

### ISSUE THREAD

**Issue by ctlajoie** [protz/GMail-Conversation-View#982]
As seen in my screenshot, the quick reply buttons don't look right when using a dark theme. Also the "In new window" links are almost impossible to read.
![screenshot](https://cloud.githubusercontent.com/assets/247708/8558288/6c7a34e6-24c0-11e5-8969-b62a31b17ebd.png)

**Comment by protz** [comment]
Thanks for the report.

This seems like a minor fix -- just a matter of using the right "special" colors (i.e. something like "moz-anchor-text" or whatever) in the CSS. Any chance you could look into it? I don't use a dark theme and I have little time on my hands.
