### ISSUE TITLE
conflict with quick folder move

### ISSUE THREAD

**Issue by pcause** [protz/GMail-Conversation-View#985]
Just tried and love this extension, but I have a problem on send.  I also use quick folder move and the way this extension sends means that I don't get the popup from quick folder move to allow me to file a message/thread on send.

**Comment by protz** [comment]
Hi,

Unfortunately I can't patch the code of quick folder to make it work with the addon; you should probably file a bug over at quick folder, and add it to the list at https://github.com/protz/GMail-Conversation-View/issues/985.

There is a "plugin" mechanism (see http://blog.xulforum.org/index.php?post/2010/11/27/Thunderbird-Conversations-plugins for an outdated overview) that the quick folder folks could certainly leverage.

Thanks,

Jonathan
