### ISSUE TITLE
Since last TB update, message contents are not visible

### ISSUE THREAD

**Issue by LaurentBarbareau** [protz/GMail-Conversation-View#988]
Hi,

I've just got the same issue than that one https://addons.mozilla.org/fr/thunderbird/addon/gmail-conversation-view/reviews/718992/ , just after the last TB update (38.1.0). Message contents were not displayed anymore...

It seems I've solved the problem just by touching the option of the extension and restarting TB.
The touched option (checkbox "I love attachments" or something similar in english) seems to have no real effect on the problem, because I have set it back into its initial state and still works, I can seen message contents...

So it was just to notify that strange problem.

Regards.

**Comment by Marooned-MB** [comment]
I can't confirm that changing some option (I've also used "I love attachments") and restarting TB fixes the issue. Still no content is visible. I have to disable this extension to see mails.

**Comment by LaurentBarbareau** [comment]
I know this is not the good solution but I had reached to see the mail content by displaying it via the "more" menu on the right.

**Comment by protz** [comment]
Just make sure your addon is uptodate (Tools > Addons) and restart thunderbird. It's an issue with Thunderbird leaving  an old version of Conversations instead of updating it.

**Comment by Marooned-MB** [comment]
Confirmed, manual "find new version" (or similar, I don't have English version) and restart TB fixes the issue.

**Comment by LaurentBarbareau** [comment]
Ok, fine. I had also made an manual update of the extensions but I hadn't noticed if something had been effectively updated. Btw, I think it can be the reason why it worked again.

Thanks a lot.
Very nice extension that should be standard in TB ... :scream:
