### ISSUE TITLE
[Feature Request] Add Filters for classic layout

### ISSUE THREAD

**Issue by sunbow** [protz/GMail-Conversation-View#989]
Hi,
I have a problem with outlook appointments. I have a plugin (Lightning) which provides a calendar for thunderbird and which shows notifications in mails which contain an appointment to add it to the calendar.

When the gmail conversation view plugin is active, that notification isn't displayed.
A simple way to get around this problem would be to add filters for classical view. So if the source code of the received mail contains a user defined string, the classsical view is activated automatically.

This would allow me to filter for something like "Content-Type: text/calendar" which is part of the source code of an outlook appointment.

**Comment by sunbow** [comment]
Hmmm... seems like there is a much bigger problem...
Not sure if Thunderbird update is responisble or an update of this addon...

However it doesn't display the content of any messages anymore. so the add on became totally useless :(

**Comment by LaurentBarbareau** [comment]
Hi, for that latter check that https://github.com/protz/GMail-Conversation-View/issues/988

**Comment by JeReT** [comment]
ok, thx. problem is fixed after updating to the latest version (had to update manually).

**Comment by protz** [comment]
Ok, closing since both the update issue and the lightning incompatibilities are known.

Thanks for the bug report,

Jonathan
