### ISSUE TITLE
gmail: "all mail" (archive) messages don't appear in conversation?

### ISSUE THREAD

**Issue by rikshaw76** [protz/GMail-Conversation-View#990]
Thanks for a great extension.  One question, however:

With gmail (imap) accounts, when "archiving" I have it set to go to gmail's "all mail" folder.  When a new message (with previous replies in the conversation archived) appears, however, these previous replies do not appear in the conversation thread.

This may be intentional, but it is different than gmail's behavior, which will show the full conversation in the inbox even if the previous messages of the conversation had previously been archived.

It is very difficult to see the "full conversation" then, if part of it has been "archived".  So for now as a "stop gap" I am not archiving anything to "all mail" but am filing things to a different folder, which has no problem.  It is just the messages that only exist in "all mail" (and no other folder on the gmail account) that do not appear in the conversation history.

So, is this a "bug" or is it "by design"?

**Comment by protz** [comment]
It depends on whether Thunderbird uses "gloda" (the global indexer) to index your "all mail" folder. I suspect this may not be the case. You can check by right-clicking on the "all mail" folder, then look around for "include this folder in global search results".

Thanks,

Jonathan

**Comment by rikshaw76** [comment]
@protz: thanks for the quick reply.

In folder properties, the Archive folder(s) -- they are assigned to Google's "All Mail" folder(s) -- are indeed set to "Include messages in this folder in Global Search results".  However, the problem persists that once messages are archived here, they will NOT show in the inbox's conversation thread when a new message to that conversation arrives.  It may be due to the fact that, once again, the "All Mail" thread is defined as my "Archive folder".

**Comment by protz** [comment]
Well they should show in the "conversation area" (where you can expand/collapse messages in the conversation view) but they won't show in the "thread pane" (message list) because that's a thunderbird thing I have no control over.

Is that what you were asking?

**Comment by rikshaw76** [comment]
@protz I do understand you don't have control over the "message list", but just the "message pane".  In my prior testing I wasn't seeing the messages in the conversation after they were archived as noted above.  

However, I think that the culprit may have been my imap folder taking a while to sync up or something, because all seems to be functioning well now.

So you are correct this a false positive and can be closed.  Sorry for the inconvenience, and thanks again for a great plugin.
