### ISSUE TITLE
plug-in is broken in latest Thunderbird update.

### ISSUE THREAD

**Issue by Maskedman** [protz/GMail-Conversation-View#991]
Disabling it fixes the issue temporarily.

**Comment by pianoslum** [comment]
Did you update manually?
See: https://github.com/protz/GMail-Conversation-View/issues/988

**Comment by Maskedman** [comment]
yes, even though thunderbird didn't detect a new version, I just uninstalled, and reinstalled new version. All good to go. Thanks for a great plug-in!
