### ISSUE TITLE
Enabling Lightning with Google Provider stops message appearing.

### ISSUE THREAD

**Issue by kiwichris** [protz/GMail-Conversation-View#992]
On a fully updated MacOS with Thunderbird 38.1.0 and Conversations 2.8.1 turning on Lightning and adding the Google Provider add-on results in no message body being displayed and clicking on a message or thread does not read it or clear the read flag, ie the message stays unread. The conversation thread is present and correct, the body and summary of the message is empty. The Error Console is showing:

Timestamp: 21/07/2015 10:46:02 am
Error: TypeError: redeclaration of formal parameter params
Source File: resource://conversations/modules/stdlib/send.js
Line: 361
Timestamp: 21/07/2015 10:46:02 am
Error: TypeError: Log is undefined
Source File: chrome://conversations/content/stub.completion-ui.js
Line: 16

**Comment by pianoslum** [comment]
Did you update manually?
See: #988

**Comment by kiwichris** [comment]
No, Thunderbird updated and I think it updated the Addon and Lightning is now included in Thunderbird. I can confirm following #988 resolved the issue. 

Many thanks for the prompt response.

**Comment by protz** [comment]
Thanks @pianoslum
