### ISSUE TITLE
Sent mail appearing in unified inbox

### ISSUE THREAD

**Issue by sginsbe** [protz/GMail-Conversation-View#993]
I suspect this has to do with the update to Thunderbird a few days ago since that's when it started happening. I'm now using Thunderbird version 38.1.0. Sent messages appear in my inbox only when using the unified inbox. This occurs even when the it's just a single message sent from me to someone else and there is not yet a reply (so not a conversation but an individual sent message). These sent messages do not appear in the inbox if I view my mail in the browser (Gmail). If I delete the message from my inbox, it deletes from my sent mail, as well. 

I tried to set up a filter to move sent mail to the sent folder but it has no effect. I went to the unified inbox properties and deselected the Sent folder but it had no effect.

**Comment by protz** [comment]
Yes, this is the "default customization" of Conversations. You can right-click on the unified inbox, hit "Properties", then "Choose", and uncheck the sent folder.

Thanks,

Jonathan

**Comment by sginsbe** [comment]
As stated in my original message, I did try that but it had no effect and sent messages continued showing up in my inbox.

**Comment by wolftune** [comment]
> You can right-click on the unified inbox, hit "Properties", then "Choose", and uncheck the sent folder.

I found I had to go also to uncheck the Sent folders for *each* account separate from the global unified Sent folder.
