### ISSUE TITLE
Possibilty to co-use of MailHops

### ISSUE THREAD

**Issue by JanKraljic** [protz/GMail-Conversation-View#994]
How would be possible to use Gmail-Conversation and MailHops ( https://addons.mozilla.org/en-US/thunderbird/addon/mailhops/ ) plugin at the same time? 

Since there are more and more scams and spam it is nice information to have flag from which country is mail originally. That is very useful specially to become aware if did not come from same as last time.

Thanks for doing great and useful plugin for TB.

**Comment by protz** [comment]
Hi,

Unfortunately, I can't modify Conversations to interact with every single other Thunderbird addon out there. That being said, I offer a "plugin" mechanism wherein another addon can "register" into Conversations and interact with it. That's how we get Lightning, Enigmail, and many others to work together. http://blog.xulforum.org/index.php?post/2010/11/27/Thunderbird-Conversations-plugins describes the architecture; there are a couple examples in the source tree.

Your best bet is to ping the mail hops author, and ask him if he can write a plugin just like enigmail or lightning does. They can even integrate the plugin *in* MailHops and don't need to sync up with me.

Thanks,

Jonathan

**Comment by JanKraljic** [comment]
Thank you for this info.
