### ISSUE TITLE
Wishlist: SeaMonkey Mail support

### ISSUE THREAD

**Issue by sphakka** [protz/GMail-Conversation-View#995]
Ditto, that would be nice :-)

**Comment by protz** [comment]
Hi,

Not being a user of SeaMonkey, and my time being fairly limited, there no chance I can look into this, unfortunately. If you have a patch ready to submit that enables SeaMonkey support with limited modifications, I'd look into it, but anything else is unlikely to happen.

Thanks,

Jonathan
