### ISSUE TITLE
No mail content is show in Thunderbird 38.2.0 (Ubuntu)

### ISSUE THREAD

**Issue by AlexHaaniWink** [protz/GMail-Conversation-View#998]
In Ubuntu 14.04 my Thunderbird was just upgraded to 38.2.0.
Now I cannot see mail contents anymore.

I had to disable the addon to keep Thunderbird usable.

**Comment by msprotz** [comment]
Your addon was not properly upgraded. Please make sure you have the latest version of the addon (Tools > Add-ons), restart Thunderbird, then close this issue. Thanks.

**Comment by mad73923** [comment]
Same problem here, upgrade fixed the issue!
close #998
