### ISSUE TITLE
Body of emails not shown in TB 38.2

### ISSUE THREAD

**Issue by joachimjacob** [protz/GMail-Conversation-View#999]
After updating today, the body of the email is not shown. It is basically completely empty.

It attach a screenshot.

Thanks.

![selectie_807](https://cloud.githubusercontent.com/assets/1138051/9488133/e8cb970e-4bd7-11e5-8a0b-c9417b8a2522.jpg)

**Comment by rivaldi8** [comment]
It was happening to me too. Not sure if I've done anything but, after a while, it has started working again, even after restarting Thunderbird.

I'll report back if it fails again.

**Comment by billboule** [comment]
Same thing here.... Inactivate and re-activate the addon solved the problem...

**Comment by joachimjacob** [comment]
Inactivating and reactivating several times, restarting thunderbird,... did not do the trick.

**Comment by besens** [comment]
Yes ! Same thing. But if I restart TB 38.2 whithout extensions : all works fine.

**Comment by AltraMayor** [comment]
I'm with @besens, once I activate the Conversation extension, my messages are shown empty.

**Comment by msprotz** [comment]
Please go to Tools > Add-ons, force Conversations to update, then restart Thunderbird. If that works for you, please close this issue. Thanks!

**Comment by joachimjacob** [comment]
Indeed, force updating works. Thanks!

**Comment by jtflynnz** [comment]
Can confirm the issue, but once I did as msprotz suggested, "check for updates" in tools > add-ons seems to find an update, which seems to make everything work (In my case I needed restarted Thunderbird and re-ran the set-up assistant).
